FROM nikolaik/python-nodejs:python3.10-nodejs16-slim

WORKDIR /usr/src/sa-frontend
COPY frontend .

# Intall required dependencies for node-gyp
RUN apt-get update && \
    apt-get install -y pkg-config libxi-dev libgl1-mesa-dev \
                       build-essential \
                       # node-canvas dependencies
                       libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

RUN yarn install --frozen-lockfile && yarn build

EXPOSE 3000
CMD [ "yarn", "start" ]
