version: "3.9"
services:
  db:
    image: postgres:14.8
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - sa-backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PG_USER=${BACKEND_DB_USER}
      - PG_DATABASE=${BACKEND_DB_NAME}
      - PG_HOST=${BACKEND_DB_HOST}
    ports:
      - 4000:4000 # TODO: Configure using env variable
    depends_on:
      - db
    networks:
      - sa-backend

networks:
  sa-backend:
    driver: bridge
