name: Run CI
on:
  push:

jobs:
  build-docker:
    name: Build Docker images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Ensures cross-platform
        os:
          # Windows users can simply use WSL for development
          - macos-12
          - macos-13
          - ubuntu-20.04
          - ubuntu-22.04
        image:
          - frontend
          - backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install and set up Docker
        if: ${{ runner.os == 'macOS'}}
        run: |
          brew install docker
          brew install docker-compose
      - name: Build frontend image
        if: ${{ matrix.image == 'frontend' }}
        run: |
          make fe-build
      - name: Build backend Docker compose
        if: ${{ matrix.image == 'backend' }}
        run: |
          cp backend-config.exs.example backend-config.exs
          make be-build
